Models update

diff --git a/nathaneltitane-update b/nathaneltitane-update
--- a/nathaneltitane-update
+++ b/nathaneltitane-update
@@ -139,6 +139,48 @@ run () {
 
 # requirements /////////////////////////////////////////////////////////////////
 
+frobulator.assess () {
+	if [[ -n "${#list[@]}" ]]
+	then
+		# ${1} - array
+
+		list=(${@:1})
+	else
+		command="${1}"
+
+		list=()
+
+		list+=("${command}")
+	fi
+
+	if [[ $(id -u -n) = "root" ]]
+	then
+		frobulator.require ${list[@]}
+
+		frobulator.msg "${script} requirements installed."
+		echo
+
+		frobulator.inf "Run ${script} as 'user' to proceed."
+		echo
+
+		exit
+	else
+		for requirement in ${list[@]}
+		do
+			if [[ -z $(command -v "${requirement}") ]]
+			then
+				frobulator.err "Missing" "[ '${requirement}' ]"
+				echo
+
+				frobulator.wrn "Start ${script} as 'root' to install requirements."
+				echo
+
+				exit 1
+			fi
+		done
+	fi
+}
+
 list=(
 	git
 	jpegoptim
